

function glyphSettings()
{
    var out = [

        {gene: 'Snca',          taxonomy: 'in_general',  glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'Cplx2',         taxonomy: 'in_general',  glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Lhx6',          taxonomy: 'in_general',  glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Col25a1',       taxonomy: 'in_general',  glyphSymbol: '^',  glyphName: 'triangleUp'},
        {gene: 'Pnoc',          taxonomy: 'in_general',  glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Rab3c',         taxonomy: 'in_general',  glyphSymbol: '<',  glyphName: 'triangleLeft'},
        {gene: 'Gad1',          taxonomy: 'in_general',  glyphSymbol: 'p',  glyphName: 'star5'},
        {gene: 'Slc6a1',        taxonomy: 'in_general',  glyphSymbol: 'h',  glyphName: 'star6'},
        {gene: 'Th',            taxonomy: 'sst',         glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'Crhbp',         taxonomy: 'sst',         glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Sst',           taxonomy: 'sst',         glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Npy',           taxonomy: 'sst',         glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Synpr',         taxonomy: 'sst',         glyphSymbol: 'x',  glyphName: 'cross'},
        {gene: 'Chodl',         taxonomy: 'sst',         glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Cort',          taxonomy: 'sst',         glyphSymbol: 'd',  glyphName: 'diamond'},
        {gene: 'Reln',          taxonomy: 'sst',         glyphSymbol: '^',  glyphName: 'triangleUp'},
        {gene: 'Serpini1',      taxonomy: 'sst',         glyphSymbol: '<',  glyphName: 'triangleLeft'},
        {gene: 'Satb1',         taxonomy: 'sst',         glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Grin3a',        taxonomy: 'sst',         glyphSymbol: 'p',  glyphName: 'star5'},
        {gene: 'Tac1',          taxonomy: 'pvalb',       glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Pvalb',         taxonomy: 'pvalb',       glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Kcnip2',        taxonomy: 'pvalb',       glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Thsd7a',        taxonomy: 'pvalb',       glyphSymbol: 'd',  glyphName: 'diamond'},
        {gene: 'Cox6a2',        taxonomy: 'pvalb',       glyphSymbol: 'v',  glyphName: 'triangleDown'},
        {gene: 'Chrm2',         taxonomy: 'pvalb',       glyphSymbol: 'p',  glyphName: 'star5'},
        {gene: 'Id2',           taxonomy: 'ngf',         glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'Hapln1',        taxonomy: 'ngf',         glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Gabrd',         taxonomy: 'ngf',         glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Cryab',         taxonomy: 'ngf',         glyphSymbol: 'x',  glyphName: 'cross'},
        {gene: 'Kit',           taxonomy: 'ngf',         glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Ndnf',          taxonomy: 'ngf',         glyphSymbol: 'd',  glyphName: 'diamond'},
        {gene: 'Nos1',          taxonomy: 'ngf',         glyphSymbol: '^',  glyphName: 'triangleUp'},
        {gene: 'Lamp5',         taxonomy: 'ngf',         glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Cplx3',         taxonomy: 'ngf',         glyphSymbol: 'h',  glyphName: 'star6'},
        {gene: 'Cadps2',        taxonomy: 'cxcl14',      glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Cxcl14',        taxonomy: 'cxcl14',      glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Ntng1',         taxonomy: 'cxcl14',      glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Cpne5',         taxonomy: 'cxcl14',      glyphSymbol: 'd',  glyphName: 'diamond'},
        {gene: 'Rgs12',         taxonomy: 'cxcl14',      glyphSymbol: 'h',  glyphName: 'star6'},
        {gene: 'Sncg',          taxonomy: 'cnr1',        glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Cnr1',          taxonomy: 'cnr1',        glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Cck',           taxonomy: 'cnr1',        glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Trp53i11',      taxonomy: 'cnr1',        glyphSymbol: 'x',  glyphName: 'cross'},
        {gene: 'Sema3c',        taxonomy: 'cnr1',        glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Syt6',          taxonomy: 'cnr1',        glyphSymbol: '^',  glyphName: 'triangleUp'},
        {gene: 'Yjefn3',        taxonomy: 'cnr1',        glyphSymbol: 'v',  glyphName: 'triangleDown'},
        {gene: 'Rgs10',         taxonomy: 'cnr1',        glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Nov',           taxonomy: 'cnr1',        glyphSymbol: '<',  glyphName: 'triangleLeft'},
        {gene: 'Kctd12',        taxonomy: 'cnr1',        glyphSymbol: 'p',  glyphName: 'star5'},
        {gene: 'Slc17a8',       taxonomy: 'cnr1',        glyphSymbol: 'h',  glyphName: 'star6'},
        {gene: 'Tac2',          taxonomy: 'vip',         glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'Npy2r',         taxonomy: 'vip',         glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Calb2',         taxonomy: 'vip',         glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Htr3a',         taxonomy: 'vip',         glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Slc5a7',        taxonomy: 'vip',         glyphSymbol: 'x',  glyphName: 'cross'},
        {gene: 'Penk',          taxonomy: 'vip',         glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Pthlh',         taxonomy: 'vip',         glyphSymbol: '^',  glyphName: 'triangleUp'},
        {gene: 'Vip',           taxonomy: 'vip',         glyphSymbol: 'v',  glyphName: 'triangleDown'},
        {gene: 'Crh',           taxonomy: 'vip',         glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Qrfpr',         taxonomy: 'vip',         glyphSymbol: 'p',  glyphName: 'star5'},
        {gene: 'Zcchc12',       taxonomy: 'less_active', glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'Calb1',         taxonomy: 'less_active', glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Vsnl1',         taxonomy: 'less_active', glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Tmsb10',        taxonomy: 'less_active', glyphSymbol: 'd',  glyphName: 'diamond'},
        {gene: 'Rbp4',          taxonomy: 'less_active', glyphSymbol: 'v',  glyphName: 'triangleDown'},
        {gene: 'Fxyd6',         taxonomy: 'less_active', glyphSymbol: '^',  glyphName: 'triangleUp'},
        {gene: '6330403K07Rik', taxonomy: 'less_active', glyphSymbol: '<',  glyphName: 'triangleLeft'},
        {gene: 'Scg2',          taxonomy: 'less_active', glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Gap43',         taxonomy: 'less_active', glyphSymbol: 'p',  glyphName: 'star5'},
        {gene: 'Nrsn1',         taxonomy: 'less_active', glyphSymbol: 'h',  glyphName: 'star6'},
        {gene: 'Gda',           taxonomy: 'pc_or_in',    glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'Bcl11b',        taxonomy: 'pc_or_in',    glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Rgs4',          taxonomy: 'pc_or_in',    glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Slc24a2',       taxonomy: 'pc_or_in',    glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Lphn2',         taxonomy: 'pc_or_in',    glyphSymbol: 'x',  glyphName: 'cross'},
        {gene: 'Adgrl2',        taxonomy: 'pc_or_in',    glyphSymbol: 'x',  glyphName: 'cross'},
        {gene: 'Map2',          taxonomy: 'pc_or_in',    glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Prkca',         taxonomy: 'pc_or_in',    glyphSymbol: 'd',  glyphName: 'diamond'},
        {gene: 'Cdh13',         taxonomy: 'pc_or_in',    glyphSymbol: '^',  glyphName: 'triangleUp'},
        {gene: 'Atp1b1',        taxonomy: 'pc_or_in',    glyphSymbol: 'v',  glyphName: 'triangleDown'},
        {gene: 'Pde1a',         taxonomy: 'pc_or_in',    glyphSymbol: '<',  glyphName: 'triangleLeft'},
        {gene: 'Calm2',         taxonomy: 'pc_or_in',    glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Sema3e',        taxonomy: 'pc_or_in',    glyphSymbol: 'h',  glyphName: 'star6'},
        {gene: 'Nrn1',          taxonomy: 'pc',          glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Pcp4',          taxonomy: 'pc',          glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Rprm',          taxonomy: 'pc',          glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'Enpp2',         taxonomy: 'pc',          glyphSymbol: 'x',  glyphName: 'cross'},
        {gene: 'Rorb',          taxonomy: 'pc',          glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Rasgrf2',       taxonomy: 'pc',          glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Wfs1',          taxonomy: 'pc',          glyphSymbol: 'd',  glyphName: 'diamond'},
        {gene: 'Fos',           taxonomy: 'pc',          glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Plcxd2',        taxonomy: 'pc',          glyphSymbol: 'v',  glyphName: 'triangleDown'},
        {gene: 'Crym',          taxonomy: 'pc',          glyphSymbol: '<',  glyphName: 'triangleLeft'},
        {gene: '3110035E14Rik', taxonomy: 'pc',          glyphSymbol: '^',  glyphName: 'triangleUp'},
        {gene: 'Foxp2',         taxonomy: 'pc',          glyphSymbol: 'p',  glyphName: 'star5'},
        {gene: 'Pvrl3',         taxonomy: 'pc',          glyphSymbol: 'h',  glyphName: 'star6'},
        {gene: 'Neurod6',       taxonomy: 'pc2',         glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'Nr4a2',         taxonomy: 'pc2',         glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Cux2',          taxonomy: 'pc2',         glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Kcnk2',         taxonomy: 'pc2',         glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Arpp21',        taxonomy: 'pc2',         glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Enc1',          taxonomy: 'pc2',         glyphSymbol: 'v',  glyphName: 'triangleDown'},
        {gene: 'Fam19a1',       taxonomy: 'pc2',         glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Vim',           taxonomy: 'non_neuron',  glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Slc1a2',        taxonomy: 'non_neuron',  glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Pax6',          taxonomy: 'non_neuron',  glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Plp1',          taxonomy: 'non_neuron',  glyphSymbol: 'x',  glyphName: 'cross'},
        {gene: 'Mal',           taxonomy: 'non_neuron',  glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'Aldoc',         taxonomy: 'non_neuron',  glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Actb',          taxonomy: 'non_neuron',  glyphSymbol: 'v',  glyphName: 'triangleDown'},
        {gene: 'Sulf2',         taxonomy: 'non_neuron',  glyphSymbol: 'p',  glyphName: 'star5'},


        {gene: '1110017D15Rik',          taxonomy: 'in_general',  glyphSymbol: '+',  glyphName: 'plus'},
        {gene: '1500015O10Rik',         taxonomy: 'in_general',  glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'A230065H16Rik',          taxonomy: 'in_general',  glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Acta2',       taxonomy: 'in_general',  glyphSymbol: '^',  glyphName: 'triangleUp'},
        {gene: 'Apod',          taxonomy: 'in_general',  glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Aqp4',         taxonomy: 'in_general',  glyphSymbol: '<',  glyphName: 'triangleLeft'},
        {gene: 'Arpc1b',          taxonomy: 'in_general',  glyphSymbol: 'p',  glyphName: 'star5'},
        {gene: 'Bsg',        taxonomy: 'in_general',  glyphSymbol: 'h',  glyphName: 'star6'},
        {gene: 'C1qa',            taxonomy: 'sst',         glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'C1qb',         taxonomy: 'sst',         glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'C1qc',           taxonomy: 'sst',         glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Cabp7',           taxonomy: 'sst',         glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Car2',         taxonomy: 'sst',         glyphSymbol: 'x',  glyphName: 'cross'},
        {gene: 'Car4',         taxonomy: 'sst',         glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Car8',          taxonomy: 'sst',         glyphSymbol: 'd',  glyphName: 'diamond'},
        {gene: 'Ccdc153',          taxonomy: 'sst',         glyphSymbol: '^',  glyphName: 'triangleUp'},
        {gene: 'Ccl4',      taxonomy: 'sst',         glyphSymbol: '<',  glyphName: 'triangleLeft'},
        {gene: 'Cd81',         taxonomy: 'sst',         glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Cd9',        taxonomy: 'sst',         glyphSymbol: 'p',  glyphName: 'star5'},
        {gene: 'Cdhr1',          taxonomy: 'pvalb',       glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Cdkn1c',         taxonomy: 'pvalb',       glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Cldn5',        taxonomy: 'pvalb',       glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Cntn1',        taxonomy: 'pvalb',       glyphSymbol: 'd',  glyphName: 'diamond'},
        {gene: 'Col4a1',        taxonomy: 'pvalb',       glyphSymbol: 'v',  glyphName: 'triangleDown'},
        {gene: 'Crip1',         taxonomy: 'pvalb',       glyphSymbol: 'p',  glyphName: 'star5'},
        {gene: 'Ctla2a',           taxonomy: 'ngf',         glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'Ctss',        taxonomy: 'ngf',         glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Dbi',         taxonomy: 'ngf',         glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Dcn',         taxonomy: 'ngf',         glyphSymbol: 'x',  glyphName: 'cross'},
        {gene: 'Doc2g',           taxonomy: 'ngf',         glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Efr3a',          taxonomy: 'ngf',         glyphSymbol: 'd',  glyphName: 'diamond'},
        {gene: 'En1',          taxonomy: 'ngf',         glyphSymbol: '^',  glyphName: 'triangleUp'},
        {gene: 'Epas1',         taxonomy: 'ngf',         glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Fa2h',         taxonomy: 'ngf',         glyphSymbol: 'h',  glyphName: 'star6'},
        {gene: 'Fabp7',        taxonomy: 'cxcl14',      glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Fbln2',        taxonomy: 'cxcl14',      glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Fbln5',         taxonomy: 'cxcl14',      glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Fcer1g',         taxonomy: 'cxcl14',      glyphSymbol: 'd',  glyphName: 'diamond'},
        {gene: 'Flt1',         taxonomy: 'cxcl14',      glyphSymbol: 'h',  glyphName: 'star6'},
        {gene: 'Fn1',          taxonomy: 'cnr1',        glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Foxj1',          taxonomy: 'cnr1',        glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Frmd4a',           taxonomy: 'cnr1',        glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Fxyd1',      taxonomy: 'cnr1',        glyphSymbol: 'x',  glyphName: 'cross'},
        {gene: 'Gfap',        taxonomy: 'cnr1',        glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Gjb1',          taxonomy: 'cnr1',        glyphSymbol: '^',  glyphName: 'triangleUp'},
        {gene: 'Gls',        taxonomy: 'cnr1',        glyphSymbol: 'v',  glyphName: 'triangleDown'},
        {gene: 'Gltp',         taxonomy: 'cnr1',        glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Gm15440',           taxonomy: 'cnr1',        glyphSymbol: '<',  glyphName: 'triangleLeft'},
        {gene: 'Gnb3',        taxonomy: 'cnr1',        glyphSymbol: 'p',  glyphName: 'star5'},
        {gene: 'Gng11',       taxonomy: 'cnr1',        glyphSymbol: 'h',  glyphName: 'star6'},
        {gene: 'Gng12',          taxonomy: 'vip',         glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'Gpr17',         taxonomy: 'vip',         glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Grb14',         taxonomy: 'vip',         glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Gsn',         taxonomy: 'vip',         glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Hexb',        taxonomy: 'vip',         glyphSymbol: 'x',  glyphName: 'cross'},
        {gene: 'Higd1b',          taxonomy: 'vip',         glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Hmgb2',         taxonomy: 'vip',         glyphSymbol: '^',  glyphName: 'triangleUp'},
        {gene: 'Hs6st2',           taxonomy: 'vip',         glyphSymbol: 'v',  glyphName: 'triangleDown'},
        {gene: 'Ifitm3',           taxonomy: 'vip',         glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Igf2',         taxonomy: 'vip',         glyphSymbol: 'p',  glyphName: 'star5'},
        {gene: 'Igfbp2',       taxonomy: 'less_active', glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'Igfbp6',         taxonomy: 'less_active', glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Igfbp7',         taxonomy: 'less_active', glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Igfbpl1',        taxonomy: 'less_active', glyphSymbol: 'd',  glyphName: 'diamond'},
        {gene: 'Irs4',          taxonomy: 'less_active', glyphSymbol: 'v',  glyphName: 'triangleDown'},
        {gene: 'Itm2a',         taxonomy: 'less_active', glyphSymbol: '^',  glyphName: 'triangleUp'},
        {gene: 'Jun', taxonomy: 'less_active', glyphSymbol: '<',  glyphName: 'triangleLeft'},
        {gene: 'Klk6',          taxonomy: 'less_active', glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Lhx8',         taxonomy: 'less_active', glyphSymbol: 'p',  glyphName: 'star5'},
        {gene: 'Ly6c1',         taxonomy: 'less_active', glyphSymbol: 'h',  glyphName: 'star6'},
        {gene: 'Lyz2',           taxonomy: 'pc_or_in',    glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'Mag',        taxonomy: 'pc_or_in',    glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Marcks',          taxonomy: 'pc_or_in',    glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Mgp',       taxonomy: 'pc_or_in',    glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Mia',         taxonomy: 'pc_or_in',    glyphSymbol: 'x',  glyphName: 'cross'},
        {gene: 'Mobp',        taxonomy: 'pc_or_in',    glyphSymbol: 'x',  glyphName: 'cross'},
        {gene: 'Mog',          taxonomy: 'pc_or_in',    glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Myl12a',         taxonomy: 'pc_or_in',    glyphSymbol: 'd',  glyphName: 'diamond'},
        {gene: 'Myl9',         taxonomy: 'pc_or_in',    glyphSymbol: '^',  glyphName: 'triangleUp'},
        {gene: 'Nfasc',        taxonomy: 'pc_or_in',    glyphSymbol: 'v',  glyphName: 'triangleDown'},
        {gene: 'Nmb',         taxonomy: 'pc_or_in',    glyphSymbol: '<',  glyphName: 'triangleLeft'},
        {gene: 'Nupr1',         taxonomy: 'pc_or_in',    glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Olig1',        taxonomy: 'pc_or_in',    glyphSymbol: 'h',  glyphName: 'star6'},
        {gene: 'Opalin',          taxonomy: 'pc',          glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'P2ry12',          taxonomy: 'pc',          glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Pde10a',          taxonomy: 'pc',          glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'Pde6g',         taxonomy: 'pc',          glyphSymbol: 'x',  glyphName: 'cross'},
        {gene: 'Pdlim2',          taxonomy: 'pc',          glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Peg3',       taxonomy: 'pc',          glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Pf4',          taxonomy: 'pc',          glyphSymbol: 'd',  glyphName: 'diamond'},
        {gene: 'Pglyrp1',           taxonomy: 'pc',          glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Pllp',        taxonomy: 'pc',          glyphSymbol: 'v',  glyphName: 'triangleDown'},
        {gene: 'Pltp',          taxonomy: 'pc',          glyphSymbol: '<',  glyphName: 'triangleLeft'},
        {gene: 'Ppp1r14a', taxonomy: 'pc',          glyphSymbol: '^',  glyphName: 'triangleUp'},
        {gene: 'Ppp1r1b',         taxonomy: 'pc',          glyphSymbol: 'p',  glyphName: 'star5'},
        {gene: 'Ptgds',         taxonomy: 'pc',          glyphSymbol: 'h',  glyphName: 'star6'},
        {gene: 'Qk',       taxonomy: 'pc2',         glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'Rarres2',         taxonomy: 'pc2',         glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Rbp1',          taxonomy: 'pc2',         glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Rgcc',         taxonomy: 'pc2',         glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Rgs5',        taxonomy: 'pc2',         glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Rhoc',          taxonomy: 'pc2',         glyphSymbol: 'v',  glyphName: 'triangleDown'},
        {gene: 'Rras2',       taxonomy: 'pc2',         glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Rsph1',           taxonomy: 'non_neuron',  glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'S100b',        taxonomy: 'non_neuron',  glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Sag',          taxonomy: 'non_neuron',  glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Sepp1',          taxonomy: 'non_neuron',  glyphSymbol: 'x',  glyphName: 'cross'},
        {gene: 'Serpinh1',           taxonomy: 'non_neuron',  glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'Sfrp5',         taxonomy: 'non_neuron',  glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Sirt2',          taxonomy: 'non_neuron',  glyphSymbol: 'v',  glyphName: 'triangleDown'},
        {gene: 'Slc17a6',         taxonomy: 'non_neuron',  glyphSymbol: 'p',  glyphName: 'star5'},
        {gene: 'Slc1a3',          taxonomy: 'in_general',  glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'Slc6a11',         taxonomy: 'in_general',  glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Snap25',          taxonomy: 'in_general',  glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Sostdc1',       taxonomy: 'in_general',  glyphSymbol: '^',  glyphName: 'triangleUp'},
        {gene: 'Sparc',          taxonomy: 'in_general',  glyphSymbol: '>',  glyphName: 'triangleRight'},
        {gene: 'Syt4',         taxonomy: 'in_general',  glyphSymbol: '<',  glyphName: 'triangleLeft'},
        {gene: 'Tagln',          taxonomy: 'in_general',  glyphSymbol: 'p',  glyphName: 'star5'},
        {gene: 'Tmem141',        taxonomy: 'in_general',  glyphSymbol: 'h',  glyphName: 'star6'},
        {gene: 'Tmem212',            taxonomy: 'sst',         glyphSymbol: '+',  glyphName: 'plus'},
        {gene: 'Trf',         taxonomy: 'sst',         glyphSymbol: 'o',  glyphName: 'circle'},
        {gene: 'Tsc22d4',           taxonomy: 'sst',         glyphSymbol: '*',  glyphName: 'asterisk'},
        {gene: 'Tspan2',           taxonomy: 'sst',         glyphSymbol: '.',  glyphName: 'point'},
        {gene: 'Ttr',         taxonomy: 'sst',         glyphSymbol: 'x',  glyphName: 'cross'},
        {gene: 'Tyrobp',         taxonomy: 'sst',         glyphSymbol: 's',  glyphName: 'square'},
        {gene: 'Ube2c',          taxonomy: 'sst',         glyphSymbol: 'd',  glyphName: 'diamond'},
        {gene: 'Vat1l',          taxonomy: 'sst',         glyphSymbol: '^',  glyphName: 'triangleUp'},
        {gene: 'Vtn',      taxonomy: 'sst',         glyphSymbol: '<',  glyphName: 'triangleLeft'},


        {gene: 'Generic',       taxonomy: 'generic',     glyphSymbol: 'o',  glyphName: 'circle'},

        ];

    return out
}

//create color ramp.
function glyphColor(y) {
    return y === 'non_neuron' ? '#FFFFFF' : //hsv: [0 0 1]);
        y === 'pc_or_in' ? '#407F59' :      //hsv: [.4 .5 .5]);
            y === 'less_active' ? '#96B38F' :   //hsv: [.3 .2 .7]);
                y === 'pc' ? '#00FF00' :            //hsv: [1/3 1 1]);
                    y === 'pc2' ? '#44B300' :           //hsv: [.27 1 .7]);
                        y === 'in_general' ? '#0000FF' :    //hsv: [2/3 1 1]);
                            y === 'sst' ? '#00B3FF' :           //hsv: [.55 1 1]);
                                y === 'pvalb' ? '#5C33FF' :         //hsv: [.7 .8 1]);
                                    y === 'ngf' ? '#FF00E6' :           //hsv: [.85 1 1]);
                                        y === 'cnr1' ? '#FF0000' :          //hsv: [ 1 1 1]);
                                            y === 'vip' ? '#FFC700' :           //hsv: [.13 1 1]);
                                                y === 'cxcl14' ? '#995C00' :        //hsv: [.1 1 .6]);
                                                    '#FD6A02';
}